import bootstrap from './css/bootstrap.min.css';
import fontawesome from './css/fontawesome-all.css';
import owlcarousel from './css/owl.carousel.css';
import owltheme from './css/owl.theme.default.css';
import animatecss from './css/animate.css';
import main_styles from './css/main_styles.css';
import responsive from './css/responsive.css';
import swipermincss from './css/swiper.min.css';
import socss from './css/so.css';
